[project]
name = "ais-dev2il-ais-power-smoothie-cook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.1",
    "pyjokes>=0.8.3",
    "rich>=14.2.0",
    "flask==0.5 "
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-html>=4.1.1",
]


scan:
   name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Scan for vulnerable dependencies
        run: |
          set -o pipefail
          echo "### 🛡️ Security Audit Results" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          uvx uv-secure --config=pyproject.toml | tee -a $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
